# deployment-main.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
      role: main
  template:
    metadata:
      labels:
        app: n8n
        role: main
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          envFrom:
            - configMapRef:
                name: n8n-config
          env:
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_ENCRYPTION_KEY
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_BASIC_AUTH_USER
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_BASIC_AUTH_PASSWORD
            - name: QUEUE_BULL_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: QUEUE_BULL_REDIS_HOST
            - name: QUEUE_BULL_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: QUEUE_BULL_REDIS_PORT
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_POSTGRESDB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: n8n-data